# Prometheus配置文件 - 生产环境
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ssl-manager'
    environment: 'production'

# 告警规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # SSL证书管理系统后端
  - job_name: 'ssl-manager-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # SSL证书管理系统前端（Nginx）
  - job_name: 'ssl-manager-frontend'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # 生产环境Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # PostgreSQL数据库监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 5s

  # Node Exporter（系统监控）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Docker容器监控 (cAdvisor已移除)
  # 原因: cgroup v2兼容性问题
  # 替代方案: 使用docker stats和node-exporter进行基础监控

  # SSL证书过期监控
  - job_name: 'ssl-cert-exporter'
    static_configs:
      - targets: ['ssl-cert-exporter:9219']
    scrape_interval: 300s  # 5分钟检查一次
    scrape_timeout: 30s
    params:
      target: ['https://your-domain.com']

  # 黑盒监控（外部服务可用性）
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://your-domain.com
        - https://your-domain.com/health
        - https://your-domain.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# 远程写入配置（可选，用于长期存储）
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置（可选）
# remote_read:
#   - url: "http://cortex:9009/api/prom/read"
